apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBOlXwKd52DduzAYsg9u7B9qrtEZNBwPeMXLOsmNXq3BUO8zd++d89u9Uu3ftU1sQxLj5l3oy2CyGGv5Av3XrMgT4DZiWgQV9/4EpHmRjpzCJgMt9MHq9nfdBjauwmpA/dNu4nI3NjqHutxGRQkSaBCxfr/Gp7tlSIKRyc6i00oOq9nUYmBq88zyhG3rJqgA/WU/1zxuSLiAvMK1Yqt9JSWR30Lv5x3iAtipRPz39NNURBMK7Khd1VNkO5aDmCVUetg7t2HeEKFifbiYScGRiE+f2RGsVvC/AGnWraOd9bGcfAfGRQjeyUVcq55G/mDH478yJlC5o0TFYUZCjBaL/Ukee9eqG0ti+7G9ilCYnXOWjkUeg9JX1egLHbDWhyrP2dT8ql0H8ZNfPe91PdFYVvRS+eaO/Px5Vrg+ILkPgrUebCC0UojJqgh5mUatAZ6gkgj3WxDunF9kqO3xnGAlxptWYHP82JSm/KNb12YvfJEsLTh2rlIFwZ9h5uHbk3on2jh0dXCO1pbxEpDsiAwfoPpZnQl8nNOGD4f6SkZ8kMMoZYRUf29ZTGqzI3WWaVQf0DpysdV3KnrNaK8NnU6R8kQeBdADSg+Y5C6FPOknbJp/wcu7p81ACTr0bEp1yfl5NjqUWcesZkN6XGbTJj7mupAjtlnotMPF3F+5AGItir0Pxnk4Ol4YadUDFFHKczSQVUCZDsxmZhs6L0sJoRODUAK8L7YUw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
