apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBghwF6zyioR080ZjVP+GbflNBb/dfIjFSft5kMyU2xIvDtKhBiZJbXvVVGM3Uwgm8QA77MHPv3Fe4IT0sEX18JmxaHfs61wY2qC3kSgGBf68yBMwaFizzNd4+bdNsu1TnmyZELpjFgM48/OD5ld/fCdYahtHBz1lxg801wHyFzmNhRopjZyEIqUsv/etmgxWwsJpwEFfZIaxI/DWdw6kmJRjhKrzXzGc5kKiyWjrgdS/u1JfSVRmKvUMCXtkK846CaH3Oi9+nF77SuAFHfvKFtor8/Yy67Z6f7WnwyqqGEt2g3cBMeYQYbphNWTGDdInajH+bYEsynirR2BITnRE5koJlUwKulFpX7A1x4APUSaHaV5y+Lf7wFJzYBvc+GleGva2aCIm0QTpdpGJuIRo6TLlPsNRAtvH8XDhX6CjoaPT/G77dN2oDUVtBv7c7nio9PBie8vRGfRHO/APStKUkXAscJFA7tnMgleeufYxPwB6Mqj34StqoZKjC0SMP1LUAnfv7iccnP46x/Cn6XHBOJJ2DGkOo+Pu49PRfTThfsRY/2RuO3k0tyOy9mSIf1VQbZzYGTqJE+TcwKujDkvehMYPZkxTMHkC456utrOS2wXXKC8ZOQp8fwE2oeWGCMkh5C0aUWEJvnXZsQN9jd37jn51kXDOvl3S9KmsFijVR3Uk1OrALxtBKuvZFgP0qtsM3svxfEI9ysJ8BqUoXa3Q1KDPL9XQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
